name: Build and Lint
on:
  push:
    branches:
      - master
  pull_request:

env:
  RUST_BACKTRACE: full

jobs:
  lint-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/rust
      - name: Lint (rustfmt)
        run: cargo fmt --all -- --check
  lint-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/rust
      - name: Lint (clippy)
        run: cargo clippy -- -D warnings
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/rust
      - name: Lint (rustdoc)
        run: env RUSTFLAGS="-D warnings" RUSTDOCFLAGS="-D rustdoc::all" cargo oro-doc
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ["dev", "release"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/rust
      - name: Build
        run: cargo build --profile ${{ matrix.profile }}
