name: Build and Lint
on:
  push:
    branches:
      - master
  pull_request:

env:
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: oro-os/fetch-oro-toolchain@master
      - name: Lint (clippy)
        run: cargo clippy -- -D warnings
      - name: Lint (rustfmt)
        run: cargo fmt --all -- --check
      - name: Lint (rustdoc)
        run: env RUSTFLAGS="-D warnings" RUSTDOCFLAGS="-D rustdoc::all" cargo oro-doc
      - name: Build (dev)
        run: cargo build --profile dev
      - name: Build (release)
        run: cargo build --profile release
